import * as A from '@effect-ts/core/Collections/Immutable/Array'
import { constant, flow, pipe } from '@effect-ts/core/Function'
import * as O from '@effect-ts/core/Option'
import { Lens } from '@effect-ts/monocle'
import { UUID } from '@effect-ts/morphic/Algebra/Primitives'
import * as SurveyCLient from '@guack/client'
import * as T from '@guack/types/ext/Effect'
import * as EO from '@guack/types/ext/EffectOption'
import { NonEmptyString } from '@guack/types/shared'
import { useCallback, useEffect, useMemo } from 'react'

import { useServiceContext } from '../infrastructure/context'
import { useFetch, useModify, useQuery } from '../infrastructure/data'

import * as Survey from './Survey'
