name: brain
version: 0.1.0.0
github: 'japiirainen/guack'
license: BSD3
author: 'Joona Piirainen'
maintainer: 'joona.piirainen@gmail.com'
copyright: '2021 Joona Piirainen'

extra-source-files:
   - README.md
   - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/brain#readme>

ghc-options:
   - -fplugin=Polysemy.Plugin

default-extensions:
   # Recommended for Polysemy
   - DataKinds
   - FlexibleContexts
   - GADTs
   - LambdaCase
   - PolyKinds
   - RankNTypes
   - ScopedTypeVariables
   - TypeApplications
   - TypeOperators
   - TypeFamilies
   - TemplateHaskell

   # Deriving extensions
   - GeneralizedNewtypeDeriving
   - DeriveGeneric
   - QuasiQuotes

   # Misc
   - OverloadedStrings

dependencies:
   - base >= 4.7 && < 5
   - aeson
   - aeson-pretty
   - servant-server
   - servant
   - time
   - wai
   - warp
   - bytestring
   - http-types
   - text
   - containers
   - polysemy
   - polysemy-plugin
   - polysemy-zoo
   - errors
   - mtl
   - directory
   - sqlite-simple
   - acid-state
   - safecopy
   - persistent
   - persistent-template
   - persistent-sqlite
   - persistent-postgresql
   - esqueleto

   # Swagger UI
   - servant-docs
   - servant-swagger
   - servant-swagger-ui
   - servant-swagger-ui-core
   - swagger2
   - lens
   - process

library:
   source-dirs: src
   ghc-options: -O2 -flate-specialise -fspecialise-aggressively

executables:
   brain:
      main: Main.hs
      source-dirs: app
      ghc-options: -threaded -rtsopts -with-rtsopts=-N -O2 -flate-specialise -fspecialise-aggressively
      dependencies:
         - brain

tests:
   brain-test:
      main: Spec.hs
      source-dirs: test
      ghc-options: -threaded -rtsopts -with-rtsopts=-N -O2 -flate-specialise -fspecialise-aggressively
      dependencies:
         - brain
         - hspec
         - QuickCheck
         - quickcheck-io
         - hspec-wai
         #- hspec-wai-json
         - wai-extra
