version: '3'

services:
   adminer:
      image: adminer:latest
      restart: always
      ports:
         - 8888:8080

   quack:
      image: postgres:latest
      restart: always
      environment:
         POSTGRES_PASSWORD: salaisuus
         POSTGRES_USER: guackamole
         POSTGRES_DB: guack-pg
      ports:
         - 5432:5432
